networks:
  trade_network:
    driver: bridge

services:
  # frontend:
  #   build:
  #     context: apps/frontend
  #   restart: unless-stopped
  #   depends_on: []
  #   volumes: [ ./apps/frontend/src:/app/src ]
  #   ports: [ 8100:8100 ]
  #   environment:
  #     PORT: 8100
  #   networks:
  #     - trade_network

  # proxy:
  #   build: apps/proxy
  #   container_name: trade_proxy
  #   restart: unless-stopped
  #   depends_on: []
  #   volumes: [ ./apps/proxy:/app ]
  #   environment: []
  #   ports: [ 80:80, 443:443 ]
  #   networks:
  #     - trade_network

  backend:
    build:
      context: apps/backend
    container_name: trade_backend
    restart: unless-stopped
    depends_on: []
    ports: [ 8080:8200 ] # Exposing backend on localhost:80
    deploy:
      resources:
        reservations:
          memory: 2g
        limits:
          memory: 8g
    environment:
      PORT: 8200
      DB_URL: jdbc:postgresql://database:5432/trade
      DB_USERNAME: trade
      DB_PASSWORD: trade
    networks:
      - trade_network

  database:
    image: postgres:17
    container_name: trade_database
    restart: unless-stopped
    depends_on: []
    ports: [5432:5432]
    environment:
      - POSTGRES_USER=trade
      - POSTGRES_PASSWORD=trade
      - POSTGRES_DB=trade
    networks:
      - trade_network
