services:
  frontend:
    build:
      context: apps/frontend
    restart: unless-stopped
    depends_on: []
    volumes: [ ./apps/frontend/src:/app/src ]
    environment:
      PORT: 8100

  proxy:
    build: apps/proxy
    container_name: trade_proxy
    restart: unless-stopped
    depends_on: []
    volumes: [ ./apps/proxy:/app ]
    environment: []
    ports: [ 80:80, 443:443 ]
