networks:
  trade_network:
    driver: bridge

services:
  # frontend:
  #   build:
  #     context: apps/frontend
  #   restart: unless-stopped
  #   depends_on: []
  #   volumes: [ ./apps/frontend/src:/app/src ]
  #   ports: [ 8100:8100 ]
  #   environment:
  #     PORT: 8100
  #   networks:
  #     - trade_network

  # proxy:
  #   build: apps/proxy
  #   container_name: trade_proxy
  #   restart: unless-stopped
  #   depends_on: []
  #   volumes: [ ./apps/proxy:/app ]
  #   environment: []
  #   ports: [ 80:80, 443:443 ]
  #   networks:
  #     - trade_network

  nginx:
    image: nginx:latest
    container_name: trade_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - trade_network

  router:
    build:
      context: apps/router
    container_name: trade_router
    restart: unless-stopped
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - trade_network

  backend1:
    build:
      context: apps/backend
    container_name: trade_backend1
    restart: unless-stopped
    ports:
      - "8081:8200"
    environment:
      PORT: 8200
      DB_URL: jdbc:postgresql://database:5432/trade
      DB_USERNAME: trade
      DB_PASSWORD: trade
    networks:
      - trade_network

  backend2:
    build:
      context: apps/backend
    container_name: trade_backend2
    restart: unless-stopped
    ports:
      - "8082:8200"
    environment:
      PORT: 8200
      DB_URL: jdbc:postgresql://database:5432/trade
      DB_USERNAME: trade
      DB_PASSWORD: trade
    networks:
      - trade_network

  database:
    image: postgres:17
    container_name: trade_database
    restart: unless-stopped
    depends_on: []
    volumes:
      - ./apps/data/database/postgres_data:/var/lib/postgresql/data
    ports: [5432:5432]
    environment:
      - POSTGRES_USER=trade
      - POSTGRES_PASSWORD=trade
      - POSTGRES_DB=trade
    networks:
      - trade_network
