services:
  frontend:
    build:
      context: apps/frontend
    restart: unless-stopped
    depends_on: []
    volumes: [ ./apps/frontend/src:/app/src ]
    ports: [ 8100:8100 ]
    environment:
      PORT: 8100

  # proxy:
  #   build: apps/proxy
  #   container_name: trade_proxy
  #   restart: unless-stopped
  #   depends_on: []
  #   volumes: [ ./apps/proxy:/app ]
  #   environment: []
  #   ports: [ 80:80, 443:443 ]

  backend:
    build:
      context: apps/backend
    container_name: trade_backend
    restart: unless-stopped
    depends_on: []
    ports: [ 8200:8200 ]
    environment:
      PORT: 8200
      DB_URL: jdbc:postgresql://database:5432/trade
      DB_USERNAME: trade
      DB_PASSWORD: trade

  database:
    build: apps/data/database
    container_name: trade_database
    restart: unless-stopped
    depends_on: []
    volumes:
      - ./apps/data/database/postgres_data:/var/lib/postgresql/data
    ports: [5432:5432]
    environment:
      - POSTGRES_USER=trade
      - POSTGRES_PASSWORD=trade
      - POSTGRES_DB=trade
