spring:
  application:
    name: matching
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

matching:
  rpc:
    queue:
      shard-id: 1  # This can be overridden with environment variables
      sell-order: matching.rpc.sellOrder.${matching.rpc.queue.shard-id}
      buy-order: matching.rpc.buyOrder.${matching.rpc.queue.shard-id}
      get-stock-prices: matching.rpc.getStockPrices.${matching.rpc.queue.shard-id}
      cancel-stock-order: matching.rpc.cancelStockOrder.${matching.rpc.queue.shard-id}
