spring:
  application:
    name: trades
  datasource:
    hikari:
      maximum-pool-size: 200
      minimum-idle: 20
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000
server:
  port: ${PORT:8080}

  tomcat:
    accept-count: 5000
    max-connections: 10000
    threads:
      max: 10000
uvictrades:
  security:
    expiration-seconds: ${TOKEN_EXPIRATION_SECONDS:86400}
    secret: ${SECRET_KEY:some-secret-key-this-is-quite-long-at-least-256-bytes-crazy}
  db:

    url: ${DB_URL:jdbc:postgresql://localhost:5432/trade}
    username: ${DB_USERNAME:trade}
    password: ${DB_PASSWORD:trade}

