global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

api:
  dashboard: false
  insecure: false

ping:
  entryPoint: traefik

providers:
  file:
    directory: .
    watch: true
